### ISSUE TITLE
Issue with ECS

### ISSUE THREAD

**Issue by artyomashigov** [daroczig/CEU-R-prod#7]
Hello,
I have completed the assignment for de3 till the end, but I am getting an error when I try to deploy a service under my cluster artyom-assignment-cluster. Task definition artyom-assignment
I have attached the video of my last steps for configuration and the screenshot of the error
Error message:
There was an error deploying artyom-assignment
Resource handler returned message: "Error occurred during operation 'ECS Deployment Circuit Breaker was triggered'." (RequestToken: f64cd8d2-688e-c32b-16e4-e2f891081a59, HandlerErrorCode: GeneralServiceException)
Could you help me with this?

https://github.com/daroczig/CEU-R-prod/assets/78270718/b4ee6141-304d-4bba-a3a6-9215fe354b0c
![image](https://github.com/daroczig/CEU-R-prod/assets/78270718/2195aaaa-ebbd-4b7a-8f9e-add94c76543f)

**Comment by daroczig** [comment]
Check your healthckeck API endpoint -- the `README` suggests to set it to `/stats` as that was implemented in the demo script, but if you don't have that in your API, it should be something else (best to set to the lightest/fastest endpoint).

Please close the issue if it solved the problem :crossed_fingers:

**Comment by artyomashigov** [comment]
Thank you very. The issue was solved.
